### ISSUE TITLE
Version is a reserved word we're misusing

### ISSUE THREAD

**Issue by robotlightsyou** [Slow-Scallion4183/Adventure-Colussus#40]
This is a small nitpick but it presents an excellent opportunity for someone wanting to get their first contribution.

In my experience 'version' is reserved for the release version of a piece of software, we're currently using it as a session counter. I think we should consider adjusting this so that our current 'version_counter()' gets renamed something like 'get_session_count()'. We should probably also be more specific with the 'counter' -> 'session_counter', and modify how it is printed in the menu screen. Then we could add a second function that would print the release version to the menu screen.

**Comment by Slow-Scallion4183** [comment]
yeah good idea :D ill change that

**Comment by Slow-Scallion4183** [comment]
renamed ```version_counter``` to ```get_session_counter```

renamed ```version``` (on main game screen) to ```session```
