### ISSUE TITLE
__main__.py errors on execution, no module adventure_colussus

### ISSUE THREAD

**Issue by robotlightsyou** [Slow-Scallion4183/Adventure-Colussus#43]
I mentioned this in the discussion, but since others are having a similar issue I thought it wise to move this to issues.

When I run \_\_main__.py from the command line I get an error that python can't import the module because the module doesn't exist.

I'm also getting errors in my IDE about not importing pydantic and pytest, but I am still able to run the testing suite so I think the \_\_main__ issue is different(I may be wrong).

Full traceback:
```
Traceback (most recent call last):
  File "/Users/adammearle/Desktop/textdev/Adventure-Colussus/adventure_colussus/__main__.py", line 1, in <module>
    from adventure_colussus import *
ModuleNotFoundError: No module named 'adventure_colussus'
```

**Comment by Slow-Scallion4183** [comment]
i am also getting this problem. i am not sure how to solve this and the only thing i can think of if changing the file structure of the game ;/

**Comment by starterfish** [comment]
Maybe not what you're after, but use the _os_ and _sys_ modules to set the current working directory. adventure_colussus is the module folder containing a few files, but you need to be in Adventure-Colussus-main to get there. Anyway this worked for me:

`#my "fix"
import os
import sys
os.chdir(r'C:\Adventure-Colussus-main')  #you only want to look at the folder
sys.path.append(os.getcwd())

#here begins the original __main__.py
from adventure_colussus import *`

Hope that helps.

**Comment by robotlightsyou** [comment]
I went with wireboy5's method and it works(be sure to use python3, python will error). If we implement starterfish's suggestion let's be sure to add a system check so that mac users won't error, please.

I think we can mark this closed, cheers for the assistance.
